### PR TITLE
Add confine option that confines file responses

### PR DESCRIPTION
**Pull request by kanongil**
The is a breaking change, since I decided to use `true` as the default value.

### CODE REVIEW

**Comment by kanongil** [comment]
The `baseDir` option should probably also apply to the `directory` handler, to prevent serving files outside of `relativeTo` by default.

I plan to amend the PR with this feature.

**Comment by kanongil** [comment]
Rebased patch and split into sub patches, renaming the option to `confine`.

I decided not to include any `confine` option for the `directory` handler, as I think it will be more of a nuisance than an actual security feature.

I plan to merge this soon unless there are any objections or concerns?

**Comment by hueniverse** [comment]
I don't get it.

I understand how this can be useful in a directory handler where you are serving content based on the request, but is there a real use case for file when you specify the file you want?

Also, directory already have this: https://github.com/hapijs/inert/blob/master/lib/directory.js#L81-L83
Is that not enough?

Seems like an odd feature for the file handler. I can see how it might be useful for the `reply.file()` method in case you pass it a runtime filename.

**Comment by kanongil** [comment]
Yeah, it is primarily targeted at `reply.file()` but also the plain file handler with a `function` based path.

The other target is the `directory` handler, where it allows me to remove the hack you mention and fix #5.

I am definitely open to change the defaults for the `file` handler if you think it will cause issues?

**Comment by hueniverse** [comment]
Ok then. I think the default for file should be `false` and for directory should be `true`.

**Comment by hueniverse** [comment]
Ok. We can give this a try. See how many people report issues.

**Comment by chrisisbeef** [comment]
@hueniverse / @kanongil  - I am curious why this PR hasn't been merged in and pushed yet? This seems to resolve this particular issue, and more importantly is solves a very real security issue. Can you guys provide us with an update on this PR?

**Pull request merged**
