### PR TITLE
Added support for brotli compression

### PR DESCRIPTION
**Pull request by nrotta**
Added support for brotli compression. The required changes to subtext and hapi have also been done and the PRs submitted for merging.

This PR implements the following: hapijs/hapi#3037

### CODE REVIEW

**Comment by nrotta** [comment]
Not sure why the CI is failing.

**Comment by kanongil** [comment]
Thanks for the PR. I would definitely like to include brotli support in inert.

I get the same test fails when I run `npm test`. These all seem to be caused by hapi not supporting `brotli` yet.

The implementation is currently a breaking change, as it reuses the existing `lookupCompressed` flag to enable this feature, and requires a specific version hapi with brotli support.

I would like to be able to select which precompressed files to look for. This can be done by changing `lookupCompressed` to take an array as argument, with `.gz` and `.br` as allowed values.
`true` could then be mapped to `['.gz', '.br']`, while `false` maps to an empty array for an easy upgrade path.

**Comment by nrotta** [comment]
Hi @kanongil. I reviewed your comments.

I might be wrong but I don't think this is a breaking change (at least on the Inert side). I tested the version on this PR using the current Hapi version (the one that doesn't support brotli) and it works exactly the same as the current Inert version (the one in the master branch). Meaning that you could potentially update to this version of Inert without updating Hapi and your app will not break.

The tests do fail because I assumed that they would be run using a version of Hapi that supported brotli. For example, tests assume that if you set 'accept-encoding' to 'br', the returned 'content-encoding' will equal 'br', which is true when tested with a brotli-supported Hapi version but is not the case with the current Hapi version. I could easily change the tests to ensure they pass either way. Although not sure if that is the right way to move forward.

Regarding, being able to select the precompressed file, this can be done by setting the 'accept-encoding' in the request header such as:

```headers: { 'accept-encoding': 'gzip' }```

Let me know what you think.

**Comment by kanongil** [comment]
I plan to support this in hapi@15 via #71.

@nrotta Thanks for the effort and please let me know if the new option will work for you.

**Pull request closed without merging**
